### ISSUE TITLE
:nail_care: Renaming the default branch from master to main

### ISSUE THREAD

**Issue by thiago-scherrer** [Lissy93/cheat-code#1]
Hello!

Since the project is new, what do you think about adopting the new GitHub standard from the start, using the main branch instead of master?

![image](https://user-images.githubusercontent.com/46422437/226339548-2447fefa-7b19-4008-92b3-3f9fbdd529d3.png)

:rocket:

**Comment by lissy93** [comment]
Heya @thiago-scherrer 
Sure, I can change that, I'll do it now :)
Sorry about that, seems my muscle memory is slow to learn!

**Comment by lissy93** [comment]
Done. `master` is now `main`

```bash
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
